# Generated by Django 2.2.4 on 2020-07-27 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg_app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=50)),
                ('quote_text', models.TextField(max_length=1000)),
                ('liked_by', models.ManyToManyField(related_name='liked_quotes', to='login_reg_app2.User')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='login_reg_app2.User')),
            ],
        ),
    ]
